# Generated by Django 4.1.4 on 2023-01-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-total_vote', 'title', '-created']},
        ),
    ]
